server:
#  port: 10002
  port: 10022

spring:
  application:
    name: domain-user-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    # 拆分数据源到独立database instance或者schema
    username: root
#    url: jdbc:mysql://127.0.0.1:3307/cloud-mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    password: 123456
    url: ${mariadb.url}
    password: ${mariadb.password}
    type: com.zaxxer.hikari.HikariDataSource
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
  # rabbitmq
  rabbitmq:
    host: 121.40.93.1
    port: 5672
    username: admin
    password: 123456
  # stream配置
  cloud:
    stream:
      bindings:
        force-logout-consumer:
          destination: force-logout-topic
          group: force-logout-group
          consumer:
            # 重试次数（默认三次）
            max-attempts: 2
        force-logout-producer:
          destination: force-logout-topic


# mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.hlkj.domain.user.pojo

########################
###mybatis mapper配置
########################
#通用mapper配置
mapper:
  mappers: com.hlkj.common.mapper.MyMapper
  not-empty: false
  identity: MYSQL
#分页插件配置
pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql

logging:
  level:
    com.hlkj.domain.item.mapper: debug

###########################
#####暴露actuator端点
#####hystrix监控使用
###########################
#配置中心github，无招胜有招（启动的时候从GitHub拉取这些属性，属性名称和GitHub配置一样，自动加载到项目中）
management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
