server:
  port: 20000
spring:
  application:
    name: eureka-server
  profiles:
    active: dev

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
   #将localhost指向本机
  instance:
    hostname: localhost

  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000